pictures = {
    1: "public/images/balanced.png",
    2: "public/images/boba.png",
    3: "public/images/bread.png",
    4: "public/images/camera.png",
    5: "public/images/cat_in_the_hat.png",
    6: "public/images/checker.png",
    7: "public/images/cloud.png",
    8: "public/images/coin.png",
    9: "public/images/cookiecat.png",
    10: "public/images/dope.png",
    11: "public/images/fish.png",
    12: "public/images/frog.png",
    13: "public/images/ghost.png",
    14: "public/images/ice_cube.png",
    15: "public/images/jordans.png",
    16: "public/images/leaf.png",
    17: "public/images/meh.png",
    18: "public/images/mountain.png",
    19: "public/images/popcorn.png",
    20: "public/images/saturn.png",
    21: "public/images/smiley.png",
    22: "public/images/torigate.png",
    23: "public/images/watermelon.png",
    24: "public/images/wave.png",
    25: "public/images/win.png"
}
